# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XW' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'RxDataSources'
    pod 'Moya'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'RxAlamofire/RxCocoa'
    pod 'XXNibBridge'
    pod 'SnapKit'
    pod 'BCColor'
    pod 'R.swift'
    pod 'ObjectMapper'
    
    target 'XWTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'XWUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
