# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XW' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'RxSwift', '~> 3.0'
#    pod 'RxSwift', '~> 3.0', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
#    pod 'RxCocoa',    '~> 3.0'
    pod 'RxDataSources'
    pod 'Moya'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'RxAlamofire/RxCocoa'
#    pod 'XXNibBridge'
    pod 'SnapKit'
    pod 'BCColor'
    pod 'R.swift'
    pod 'ObjectMapper'
#    pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-4'
    pod 'SVProgressHUD'
    pod 'Moya'
    pod 'Kingfisher'
    pod 'Kanna'
    pod 'AttributedLib'
    pod 'FDFullscreenPopGesture'
#    pod 'ImageScout'
#    pod 'SwiftRichString', '~> 0.9.9'

    target 'XWTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'XWUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
